version: '3.4'

services:
  store:
    image: ${DOCKER_REGISTRY-}store
    build:
      context: .
      dockerfile: Store/Dockerfile

  store.inventoryapi:
    image: ${DOCKER_REGISTRY-}storeinventoryapi
    build:
      context: .
      dockerfile: Store.InventoryApi/Dockerfile


  store.productapi:
    image: ${DOCKER_REGISTRY-}storeproductapi
    build:
      context: .
      dockerfile: Store.ProductApi/Dockerfile

